### PR TITLE
Configurable syntax (WIP)

### PR DESCRIPTION
**Pull request by TheoWinterhalter**
The syntax is now entirely handled with type classes, making the user provide their own implementation (for instance, our previous inductive type) or even work with abstract syntax as we do for our theorems.

This is still work in progress as `checking_tactics.v` compiles but does not produce a working `magic` tactic on the new syntax.

### CODE REVIEW

**Comment by TheoWinterhalter** [comment]
The tactic is now fixed, however we lost injectivity of constructors: eg. we cannot derive a contradiction from `ctxempty = ctxextend G A`, and worst of all, coq doesn't deduce it on its own.

**Comment by andrejbauer** [comment]
Isn't it a bit too early to make a PR for this branch? It looks unfinished.

**Comment by TheoWinterhalter** [comment]
Yes it is, I just wanted to open it to keep track of the development in one place but maybe this isn't the right way to go. If you want we can close it and then reopen in due time.

**Comment by TheoWinterhalter** [comment]
Subsumed by work on *syntax-as-class* branch instead.
We can keep the branch for it dealt with more things.

**Pull request closed without merging**
